src/main/kotlin/no/nav/sifinnsynapi/omsorgspenger/utvidetrett/OmsorgspengerUtvidetRettHendelseKonsument.kt
src/test/kotlin/no/nav/sifinnsynapi/FellesTestMedAlleSøknader.kt
src/test/kotlin/no/nav/sifinnsynapi/omsorgspenger/utvidetrett/OmsorgspengerUtvidetRettHendelseKonsumentIntegrasjonsTest.kt

Fikser deserialiserinfsfeil på omsorgspenger utvidet rett.

---

src/main/kotlin/no/nav/sifinnsynapi/SifInnsynApiApplication.kt
src/main/kotlin/no/nav/sifinnsynapi/soknad/SøknadMetricService.kt
src/main/kotlin/no/nav/sifinnsynapi/soknad/SøknadRepository.kt
src/main/resources/application-prod-gcp.yml
src/main/resources/application.yml
src/test/kotlin/no/nav/sifinnsynapi/soknad/SøknadRepositoryTest.kt
src/test/resources/application-test.yml

Metrikkene kan verifiseres her: https://sif-innsyn-api.dev.nav.no/actuator/prometheus

Legger til custom metrics for måling av antall søknader og søkere.

---

src/main/resources/application-prod-gcp.yml

Dette er for å forhindre at flere dittnav beskjeder blir sendt ut med feil lenke.

Disabler konsumering av pp-sykt barn i prod.

---

nais/dev-gcp.json
nais/prod-gcp.json
src/main/kotlin/no/nav/sifinnsynapi/pleiepenger/syktbarn/PleiepengerSyktBarnHendelseKonsument.kt
src/main/resources/application-prod-gcp.yml

- Setter maxReplics til 2 igjen
- Fjerner Schedulert jobb for å hente opp søknader fra database og sende ut dittnav beskjed for de.
- Aktiverer konsumering av pleiepengesøknader i prod igjen.

HOTFIX - Del 2

---

nais/dev-gcp.json
nais/prod-gcp.json
src/main/kotlin/no/nav/sifinnsynapi/pleiepenger/syktbarn/PleiepengerSyktBarnHendelseKonsument.kt
src/main/resources/application-prod-gcp.yml

Sender ut dittnav meldinger på nytt.

---

nais/dev-gcp.json
nais/prod-gcp.json
src/main/kotlin/no/nav/sifinnsynapi/pleiepenger/syktbarn/PleiepengerSyktBarnHendelseKonsument.kt
src/main/resources/application-prod-gcp.yml

Fjerner hotfix endringer

---

docker-compose-env/oneshot.json
src/main/kotlin/no/nav/sifinnsynapi/common/Søknadstype.kt
src/main/kotlin/no/nav/sifinnsynapi/config/Topics.kt
src/main/kotlin/no/nav/sifinnsynapi/dittnav/DittnavService.kt
src/main/kotlin/no/nav/sifinnsynapi/dittnav/K9Beskjed.kt
src/main/kotlin/no/nav/sifinnsynapi/dittnav/OmsorgspengerMidlertidigAleneBeskjedProperties.kt
src/main/kotlin/no/nav/sifinnsynapi/omsorgspenger/midlertidigalene/OmsorgspengerMidlertidigAleneKonsument.kt
src/main/kotlin/no/nav/sifinnsynapi/pleiepenger/syktbarn/PleiepengerSyktBarnHendelseKonsument.kt
src/main/resources/application-prod-gcp.yml
src/main/resources/application.yml
src/test/kotlin/no/nav/sifinnsynapi/common/TransactionRollbackTest.kt
src/test/kotlin/no/nav/sifinnsynapi/omsorgspenger/midlertidigalene/OmsorgspengerMidlertidigAleneKonsumentTest.kt
src/test/kotlin/no/nav/sifinnsynapi/pleiepenger/syktbarn/PleiepengerSyktBarnHendelseKonsumentIntegrasjonsTest.kt
src/test/kotlin/no/nav/sifinnsynapi/utils/KafkaUtils.kt

Konsumerer på cleanup topicen til midlertidig-alene og sender ut varsel. Lagrer ikke søknaden

Ditt NAV varsel for omsorgspenger-midlertidig-alene 

---

src/main/resources/application.yml

Legger til appnavn på transaksjonid-prefix.

---

.github/workflows/apply-alerts.yml
.github/workflows/build-and-deploy.yml
README.md
nais/alerterator-dev.yml
nais/alerterator-prod.yml
nais/alerterator.yml
src/main/kotlin/no/nav/sifinnsynapi/config/KafkaConfig.kt
src/main/resources/application-prod-gcp.yml

Legger til authorizationExceptionRetryInterval på container for å gjenforsøke authentication hver 10s.
Legger til alert for å varsle dersom det ikke er mottatt noen søknader på 48 timer.

Håndterer kafka unauthorizedException

---

src/main/kotlin/no/nav/sifinnsynapi/common/SøknadsHendelse.kt
src/main/kotlin/no/nav/sifinnsynapi/config/Topics.kt
src/main/kotlin/no/nav/sifinnsynapi/dittnav/OmsorgsdagerMeldingBeskjedProperties.kt
src/main/kotlin/no/nav/sifinnsynapi/omsorgsdager/melding/OmsorgsdagerMeldingKonsument.kt
src/main/kotlin/no/nav/sifinnsynapi/soknad/SøknadController.kt
src/main/resources/application-prod-gcp.yml
src/main/resources/application.yml
src/test/kotlin/no/nav/sifinnsynapi/omsorgsdager/melding/OmsorgsdagerMeldingKonsumentTest.kt
src/test/kotlin/no/nav/sifinnsynapi/utils/SøknadUtils.kt

Har lagt det opp slik at hver av tre ulike overføringene har sine egne properties, slik at vi kan endre enkeltvis i fremtiden hvis det er nødvendig.

Sender ut ditt Nav varsel til brukere ved deling av omsorgsdager

---

build.gradle.kts
dependabot/build.gradle

Oppdaterer avhengigheter

---

src/main/kotlin/no/nav/sifinnsynapi/dittnav/OmsorgspengerUtvidetRettBeskjedProperties.kt
src/main/kotlin/no/nav/sifinnsynapi/omsorgspenger/utvidetrett/OmsorgspengerUtvidetRettHendelseKonsument.kt
src/main/resources/application.yml
src/test/kotlin/no/nav/sifinnsynapi/omsorgspenger/utvidetrett/OmsorgspengerUtvidetRettHendelseKonsumentTest.kt

Konsumerer omsorgspengesøknader og publiserer til dittnav.

---

src/main/resources/application-prod-gcp.yml

Aktiverer konsumering i prod.

---

src/main/kotlin/no/nav/sifinnsynapi/dittnav/OmsorgspengerutbetalingArbeidstakerBeskjedProperties.kt
src/main/kotlin/no/nav/sifinnsynapi/dittnav/OmsorgspengerutbetalingSNFBeskjedProperties.kt
src/main/kotlin/no/nav/sifinnsynapi/omsorgspenger/utbetaling/arbeidstaker/OmsorgspengerutbetalingArbeidstakerHendelseKonsument.kt
src/main/kotlin/no/nav/sifinnsynapi/omsorgspenger/utbetaling/snf/OmsorgspengerutbetalingSNFHendelseKonsument.kt
src/main/resources/application-prod-gcp.yml
src/main/resources/application.yml
src/test/kotlin/no/nav/sifinnsynapi/omsorgspenger/utbetaling/OmsorgspengerutbetalingArbeidstakerHendelseKonsumentTest.kt
src/test/kotlin/no/nav/sifinnsynapi/omsorgspenger/utbetaling/OmsorgspengerutbetalingSNFHendelseKonsumentTest.kt

- https://github.com/navikt/omsorgspengerutbetalingsoknad-arbeidstaker-mottak/pull/25
- https://github.com/navikt/omsorgspengerutbetalingsoknad-mottak/pull/26

Publiserer dittnav meldinger for omsorgspengerutbetaling snf og arbeidstaker

---

src/main/kotlin/no/nav/sifinnsynapi/common/AktørId.kt

Maskerer aktørId

---

src/main/resources/handlebars/informasjonsbrev-til-arbeidsgiver.hbs

Justerer tittel og innhold på bekreftelse til arbeidsgiver.

---

src/main/kotlin/no/nav/sifinnsynapi/soknad/SøknadController.kt
src/test/kotlin/no/nav/sifinnsynapi/common/SøknadControllerTest.kt

Decoder filnavn til UTF_8 charset om det er encodet.

---

.github/workflows/build-and-deploy.yml
build.gradle.kts

- Closes #76
- Closes #75
- Closes #73
- Closes #72
- Closes #51

Oppgraderer actions og gradle plugins.

---

build.gradle.kts
src/test/resources/application-test.yml

- Fjerner scala-library da det er fikset i nyere versjon av spring-kafka.
- Fjerner eksplitt spring.profiles.active. Profil introspekteres basert på filnavn i nyere versjon av spring-boot.
- Closes #82
- Closes #81
- Closes #80
- Closes #78
- Closes #59

Oppgraderer spring boot og andre pakker.

---

build.gradle.kts

- Closes #87
- Closes #86
- Closes #85
- Closes #84

Oppgraderer diverse pakker.

---

nais/dev-gcp.json
nais/prod-gcp.json

Legger k9-selvbetjening-oppslag til i externalhosts.

---

nais/dev-gcp.json
nais/naiserator.yml
nais/prod-gcp.json

Legger til azure klient

---

src/main/kotlin/no/nav/sifinnsynapi/konsument/dokumentjournalforing/JoarkHendelseKonsument.kt

Håndterer NPE når sak/fagsakId er null.

---

src/main/kotlin/no/nav/sifinnsynapi/config/kafka/JoarkKafkaConfig.kt
src/main/kotlin/no/nav/sifinnsynapi/soknad/SøknadService.kt
src/main/kotlin/no/nav/sifinnsynapi/sts/STSClient.kt

Filtrerer ut journalposter som ikke er tilkoblet en søknad i databasen.

Filtrer ut journalposter.

---

build.gradle.kts
src/test/kotlin/no/nav/sifinnsynapi/konsument/OnpremKafkaHendelseKonsumentIntegrasjonsTest.kt

- Closes #114
- Closes #118
- Closes #119
- Closes #120
- Closes #122

Oppgradererer spring, token-validation, openhtmltopdf og plugins.

---

nais/prod-gcp.json

Dette for å fikse en gammel melding på topic som henger igjen med en offset som ikke lenger eksisterer.
Se logg for suksessfull prosessert melding: https://logs.adeo.no/goto/252903482729d9c65b8bf984b650c098
Se logg for feilende melding: https://logs.adeo.no/goto/72e4e4ff83c26a164e22478a1c91b211

Setter auto.offset.reset til latest.

---

build.gradle.kts

- closes #126
- closes #127
- closes #128
- closes #129

Oppgraderer Gradle plugins og Spring Boot

---

build.gradle.kts

Oppgraderer graphql plugin og graphql klient.

---

src/main/kotlin/no/nav/sifinnsynapi/soknad/SøknadController.kt
src/test/kotlin/no/nav/sifinnsynapi/soknad/SøknadControllerTest.kt

Generer filnavn basert på org.nummer.

Fjerner støtte for filnavn gjennom apiet.

---

docker-compose-env/oneshot.json
nais/prod-gcp.json
src/main/kotlin/no/nav/sifinnsynapi/config/Topics.kt
src/main/kotlin/no/nav/sifinnsynapi/konsument/pleiepenger/syktbarn/PleiepengerSyktBarnHendelseKonsument.kt
src/main/resources/application.yml
src/test/kotlin/no/nav/sifinnsynapi/konsument/OnpremKafkaHendelseKonsumentIntegrasjonsTest.kt
src/test/kotlin/no/nav/sifinnsynapi/utils/KafkaUtils.kt
src/test/resources/application-test.yml

Migrerer til å konsumere PP fra Aiven i stedet for onprem.

Konsumerer PP fra Aiven Kafka.

---

build.gradle.kts
nais/dev-gcp.json
nais/prod-gcp.json
src/main/kotlin/no/nav/sifinnsynapi/Routes.kt
src/main/kotlin/no/nav/sifinnsynapi/k9sakinnsynapi/K9SakInnsynApiClientConfig.kt
src/main/kotlin/no/nav/sifinnsynapi/k9sakinnsynapi/K9SakInnsynApiService.kt
src/main/kotlin/no/nav/sifinnsynapi/k9sakinnsynapi/K9SakInnsynSøknadController.kt
src/main/resources/application-dev-gcp.yml
src/main/resources/application-prod-gcp.yml
src/main/resources/application.yml
src/test/resources/application-test.yml

- Legger til endepunkt for å hente søknader fra k9-sak-innsyn-api.
- Legger til k9-format:soknad da data hentet fra k9-sak-innsyn-api inneholder dette formatet.

Integrerer mot k9-sak-innsyn-api for oppslag av søknadsopplysninger fra k9-sak.

---

build.gradle.kts

- Closes #147
- Closes #148
- Closes #149
- Closes #150
- Closes #151

Oppgraderer Spring Boot, plugins og dependency.

---

src/main/kotlin/no/nav/sifinnsynapi/konsument/pleiepenger/syktbarn/PleiepengersøknadUtils.kt
src/test/kotlin/no/nav/sifinnsynapi/soknad/SøknadServiceTest.kt

Renamer funnetOrg til organisasjon, da funnetOrg høres ut som en boolsk verdi.
Legger til test som sjekker om array fungerer.

Støtter det nye formatet hvor arbeidsgivere ligger som en arrray og ikke som objekt.

---

src/main/kotlin/no/nav/sifinnsynapi/SifInnsynApiApplication.kt
src/main/kotlin/no/nav/sifinnsynapi/konsument/dokumentjournalforing/JoarkHendelseKonsument.kt
src/main/kotlin/no/nav/sifinnsynapi/soknad/SøknadRepository.kt
src/main/resources/application.yml
src/test/kotlin/no/nav/sifinnsynapi/konsument/OnpremKafkaHendelseKonsumentIntegrasjonsTest.kt
src/test/kotlin/no/nav/sifinnsynapi/soknad/SøknadControllerTest.kt

Rydder opp i resetting av sak-id.

---

src/main/kotlin/no/nav/sifinnsynapi/http/ExceptionHandler.kt
src/main/kotlin/no/nav/sifinnsynapi/oppslag/OppslagsService.kt
src/test/kotlin/no/nav/sifinnsynapi/oppslag/OppslagsServiceTest.kt
src/test/kotlin/no/nav/sifinnsynapi/soknad/SøknadControllerTest.kt

Håndterer 451 feil (tilgang nektet) ved aktørId oppslag.

---

docker-compose-env/oneshot.json
nais/prod-gcp.json
src/main/kotlin/no/nav/sifinnsynapi/common/Søknadstype.kt
src/main/kotlin/no/nav/sifinnsynapi/config/Topics.kt
src/main/kotlin/no/nav/sifinnsynapi/konsument/ettersending/K9EttersendingBeskjedProperties.kt
src/main/kotlin/no/nav/sifinnsynapi/konsument/ettersending/K9EttersendingKonsument.kt
src/main/kotlin/no/nav/sifinnsynapi/soknad/SøknadService.kt
src/main/resources/application-prod-gcp.yml
src/main/resources/application.yml
src/test/kotlin/no/nav/sifinnsynapi/konsument/OnpremKafkaHendelseKonsumentIntegrasjonsTest.kt
src/test/kotlin/no/nav/sifinnsynapi/utils/SøknadUtils.kt

Konsumerer, lagrer, varsler dittnav for meldinger om ettersendelse.

---

nais/prod-gcp.json
src/main/resources/application-prod-gcp.yml

Skrur av dryRun og setter auto-offset-reset til none.

---

src/main/kotlin/no/nav/sifinnsynapi/konsument/pleiepenger/syktbarn/PleiepengerSyktBarnHendelseKonsument.kt
src/main/resources/application-prod-gcp.yml
src/main/resources/application.yml

Endrer dittnav beskjed med lenke til innsyn.

---

src/main/kotlin/no/nav/sifinnsynapi/dokument/DokumentService.kt

Debugger dokumentInfo pga. NPE på linje 55.

---

src/main/kotlin/no/nav/sifinnsynapi/dokument/DokumentService.kt
src/test/kotlin/no/nav/sifinnsynapi/dokument/DokumentServiceTest.kt

Håndterer NPE der brevkode kan være null.

---

.github/workflows/build-and-deploy.yml
build.gradle.kts
src/main/kotlin/no/nav/sifinnsynapi/config/kafka/CustomKafkaProperties.kt
src/main/kotlin/no/nav/sifinnsynapi/config/kafka/JoarkKafkaConfig.kt
src/main/resources/application-dev-gcp.yml
src/main/resources/application-prod-gcp.yml
src/test/resources/application-test.yml

Bruker konfigurerte credentials for innlogging mot schema registry.

Fikser konsumering av joarkhendelser fra aiven kafka.

---

src/main/kotlin/no/nav/sifinnsynapi/common/Søknadstype.kt
src/main/kotlin/no/nav/sifinnsynapi/config/Topics.kt
src/main/kotlin/no/nav/sifinnsynapi/dittnav/DittnavService.kt
src/main/kotlin/no/nav/sifinnsynapi/dittnav/K9Beskjed.kt
src/main/kotlin/no/nav/sifinnsynapi/dokument/DokumentService.kt
src/main/kotlin/no/nav/sifinnsynapi/konsument/ettersending/K9EttersendingKonsument.kt
src/main/kotlin/no/nav/sifinnsynapi/konsument/pleiepenger/endringsmelding/PleiepengerEndringsmeldingDittnavBeskjedProperties.kt
src/main/kotlin/no/nav/sifinnsynapi/konsument/pleiepenger/endringsmelding/PleiepengerEndringsmeldingHendelseKonsument.kt
src/main/kotlin/no/nav/sifinnsynapi/konsument/pleiepenger/syktbarn/PleiepengerDittnavBeskjedProperties.kt
src/main/kotlin/no/nav/sifinnsynapi/konsument/pleiepenger/syktbarn/PleiepengerSyktBarnHendelseKonsument.kt
src/main/kotlin/no/nav/sifinnsynapi/soknad/Søknad.kt
src/main/kotlin/no/nav/sifinnsynapi/soknad/SøknadService.kt
src/main/resources/application-prod-gcp.yml
src/main/resources/application.yml
src/test/kotlin/no/nav/sifinnsynapi/konsument/KafkaHendelseKonsumentIntegrasjonsTest.kt
src/test/kotlin/no/nav/sifinnsynapi/konsument/KafkaTransactionRollbackTest.kt
src/test/kotlin/no/nav/sifinnsynapi/utils/SøknadUtils.kt

Refaktorerer til felles metode for tilSøknadDAO og byggK9Beskjed.

Konsumere PP endringsmelding og lagre denne i db. 

---

src/main/kotlin/no/nav/sifinnsynapi/k9sakinnsynapi/K9SakInnsynApiClientConfig.kt
src/main/resources/application-dev-gcp.yml
src/main/resources/application-prod-gcp.yml
src/test/kotlin/no/nav/sifinnsynapi/soknad/SøknadControllerTest.kt
src/test/resources/application-test.yml

Legger til tokenx issuer og konfigurerer tokenx klient mot k9-sak-innsyn-api.

---

nais/dev-gcp.json
nais/prod-gcp.json
src/main/kotlin/no/nav/sifinnsynapi/oppslag/OppslagsKlientKonfig.kt
src/main/resources/application-dev-gcp.yml
src/main/resources/application-prod-gcp.yml
src/test/kotlin/no/nav/sifinnsynapi/konsument/KafkaHendelseKonsumentIntegrasjonsTest.kt
src/test/resources/application-test.yml

Utveksler token med tokenx før kall på k9-selvbetjening-oppslag.

---

build.gradle.kts
src/main/kotlin/no/nav/sifinnsynapi/config/WebMvcConfig.kt
src/main/kotlin/no/nav/sifinnsynapi/konsument/pleiepenger/endringsmelding/PleiepengerEndringsmeldingHendelseKonsument.kt
src/test/kotlin/no/nav/sifinnsynapi/dokument/DokumentControllerTest.kt
src/test/kotlin/no/nav/sifinnsynapi/saf/SafServiceTest.kt
src/test/kotlin/no/nav/sifinnsynapi/soknad/SøknadControllerTest.kt
src/test/kotlin/no/nav/sifinnsynapi/utils/KafkaUtils.kt

Oppgraderer plugins og dependencies

---

src/main/kotlin/no/nav/sifinnsynapi/k9sakinnsynapi/K9SakInnsynApiService.kt

Får ikke lenger et objekt fra k9-sak-innsyn-api men et string som inneholder fnr på barnet.

Refaktorerer barn til pleietrengendeIdent.

---

src/main/kotlin/no/nav/sifinnsynapi/safselvbetjening/SafSelvbetjeningService.kt
src/main/kotlin/no/nav/sifinnsynapi/util/TokenUtils.kt

Fikser henting av pid/sub fra token.

---

Dockerfile
scripts/apiKey-from-vault-to-kubernetes-secrets.sh

Erstatter navikt/java:17 med distroless/java17.

---

nais/dev-gcp.json
nais/naiserator.yml
nais/prod-gcp.json

Bruker service-discovery for oppslag.

---

nais/dev-gcp.json
nais/naiserator.yml
nais/prod-gcp.json

Bruker service discovery ved kall til k9-sak-innsyn-api

---

src/main/kotlin/no/nav/sifinnsynapi/oppslag/OppslagsService.kt

Kjører retry på oppslag ved unauthorized response.

---

build.gradle.kts

- closes #233
- closes #232
- closes #231
- closes #230
- closes #225

Oppgraderer pakker og plugins.

---

build.gradle.kts

Oppdaterer graphql.

---

src/main/kotlin/no/nav/sifinnsynapi/konsument/ettersending/K9EttersendingKonsument.kt
src/main/kotlin/no/nav/sifinnsynapi/konsument/pleiepenger/endringsmelding/PleiepengerEndringsmeldingHendelseKonsument.kt
src/main/kotlin/no/nav/sifinnsynapi/konsument/pleiepenger/syktbarn/PleiepengerSyktBarnHendelseKonsument.kt
src/main/kotlin/no/nav/sifinnsynapi/soknad/SøknadRepository.kt

https://medium.com/javarevisited/i-was-scolded-by-the-boss-because-i-didnt-add-rollbackfor-exception-class-to-transactional-68cbeaea28a0

Ruller tilbake ved check exception.

---

build.gradle.kts

- closes #254
- closes #251
- closes #249

Oppgraderer plugins, og diverse pakker.

---

src/main/resources/handlebars/informasjonsbrev-til-arbeidsgiver.hbs

Tekstendringer - bekreftelse til arbeidsgiver

---

build.gradle.kts

Bunper confluentVersion

---

src/main/kotlin/no/nav/sifinnsynapi/konsument/ettersending/K9EttersendingKonsument.kt
src/test/kotlin/no/nav/sifinnsynapi/konsument/KafkaHendelseKonsumentIntegrasjonsTest.kt
src/test/kotlin/no/nav/sifinnsynapi/utils/SøknadUtils.kt

- Refaktorerer test av ettersending med parameterized test for enum Ettersendelsestype.

Støtter OMP_UTV_AO som ettersendelsestype.

---

src/main/kotlin/no/nav/sifinnsynapi/dittnav/DittnavService.kt
src/main/kotlin/no/nav/sifinnsynapi/mikrofrontend/MikrofrontendRepository.kt
src/main/kotlin/no/nav/sifinnsynapi/mikrofrontend/MikrofrontendScheduler.kt
src/main/kotlin/no/nav/sifinnsynapi/mikrofrontend/MikrofrontendService.kt
src/main/kotlin/no/nav/sifinnsynapi/soknad/SøknadRepository.kt
src/main/kotlin/no/nav/sifinnsynapi/soknad/SøknadService.kt
src/test/kotlin/no/nav/sifinnsynapi/mikrofrontend/MikrofrontendSchedulerTest.kt
src/test/kotlin/no/nav/sifinnsynapi/soknad/SøknadRepositoryTest.kt
src/test/kotlin/no/nav/sifinnsynapi/utils/KafkaUtils.kt
src/test/kotlin/no/nav/sifinnsynapi/utils/WiremockStub.kt
src/test/resources/application-test.yml

- Fikser transaksjonsproblemer med scheulert jobb. Committer transaksjon for hver melding.
- Schedulert jobb er satt til å kjøre en gang og leser inn entitene 1000 rader om gangen.
- For hver batch så vil status på radene endre seg, og vil ikke være med i neste sql spørring

Deaktiverer dine-pleiepenger mikrofrontend

---

src/main/kotlin/no/nav/sifinnsynapi/mikrofrontend/MikrofrontendRepository.kt
src/main/kotlin/no/nav/sifinnsynapi/mikrofrontend/MikrofrontendScheduler.kt
src/main/kotlin/no/nav/sifinnsynapi/mikrofrontend/MikrofrontendService.kt
src/main/kotlin/no/nav/sifinnsynapi/soknad/SøknadRepository.kt
src/main/kotlin/no/nav/sifinnsynapi/soknad/SøknadService.kt
src/main/resources/db/migration/V6__clear_mikrofrontend.sql
src/test/kotlin/no/nav/sifinnsynapi/mikrofrontend/MikrofrontendSchedulerTest.kt
src/test/kotlin/no/nav/sifinnsynapi/soknad/SøknadRepositoryTest.kt
src/test/kotlin/no/nav/sifinnsynapi/utils/KafkaUtils.kt

Tømmer mikrofrontend tabellen og populerer den på nytt med aktiverte dine-pleiepenger mikrofrontend for pleiepengesøknader innsendt siste 6 måneder.

Schedulerer jobb for aktivering av dine-pleiepenger for søknader innsendt de siste 6 måneder.
